// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnwbuvffpdmbohsqkypw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRud2J1dmZmcGRtYm9oc3FreXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTc1NDUsImV4cCI6MjA3MjM5MzU0NX0.uI7Lg5NNtmPP9k-qL7hOxfT5TSfoWHNWaUOOi-kqAZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});